### ISSUE TITLE
Training of custom dataset

### ISSUE THREAD

**Issue by harjatinsingh** [wasidennis/AdaptSegNet#1]
Are there guidelines on running the network on custom dataset ?

**Comment by Aayushktyagi** [comment]
Hi ,
Thanks @hfslyc  for sharing code.
I am trying to run the network on the custom dataset. My dataset contains binary mask.
I created custom data loader for both source and target.
I am facing issue with loading model. 
1) I used deep labs with single class I am getting the following error while I am using deep labs with num_classes = 1

![Screenshot from 2020-01-27 15-56-10](https://user-images.githubusercontent.com/32107805/73167360-bf720880-411d-11ea-98c3-f6ab211aaf53.png)

2) Can you please guide me which changes need to be done when training model from scratch.
![Screenshot from 2020-01-27 16-01-08](https://user-images.githubusercontent.com/32107805/73167672-445d2200-411e-11ea-8453-3ab968a1b530.png)

Thanks in advance 
Aayush
