### ISSUE TITLE
Cityscapes Test result

### ISSUE THREAD

**Issue by InstantWindy** [wasidennis/AdaptSegNet#12]
Does your Cityscapes test dataset have labels?I have downloaded a label without a test data set from the official website.So I can't get the test mean IOU. Thank you!

**Comment by hfslyc** [comment]
Hi,

You can only get the test set performance through submitting the results to their website. In this work, we only evaluate on the val set.

**Comment by InstantWindy** [comment]
What should I submit to this website? Is the predicted tag value or the predicted image？ Thank you!

**Comment by wasidennis** [comment]
If you'd like to submit result on the test set of Cityscapes, you should create an account on their website and follow the instructions. Normally, we just evaluate the performance on the validation set where we have the ground truth annotations and the evaluation code.
