### ISSUE TITLE
RuntimeError: there are no graph nodes that require computing gradients

### ISSUE THREAD

**Issue by yaxingwang** [wasidennis/AdaptSegNet#13]
Hi, Thank you for sharing your code. I met a problem which is as follows:

### **Traceback (most recent call last):
  File "train_gta2cityscapes_multi.py", line 412, in <module>
    main()
  File "train_gta2cityscapes_multi.py", line 304, in main
    loss.backward()
  File "/home/yaxing/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/yaxing/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
RuntimeError: there are no graph nodes that require computing gradients**

Note I never change the code.
During training, the error happens instead of the beginning. There are three times(iter:25281/25000, 8500/25000, 600/25000 ). 
The pytorch is 0.2.0_4 with python2.7.

please forgive me to bother you

**Comment by wasidennis** [comment]
Thanks for reporting it. We used the same pytorch version as you used but have never found such errors during training. Have you solved the problem somehow?

**Comment by yaxingwang** [comment]
Hi, @wasidennis @renjie130, I have fixed the problem, which is from Anaconda. I used the anaconda to build virtual environments and install pytorch,  which is not stable, in fact, I do not know why. What I do is to install pytorch instead of using anaconda, then run the released code. At moment, the code is performed one day,  I think it is fine.

**Comment by wasidennis** [comment]
Hi @yaxingwang, I have been using anaconda to run our code without having troubles. Maybe it is unstable and thanks a lot for your updates!

**Comment by yaxingwang** [comment]
Hi @wasidennis, Thank you for sharing your code. I have been running for three days and the result is similar to what you show in your paper, which is very cool.
