### ISSUE TITLE
Change Class Number

### ISSUE THREAD

**Issue by yoshinobu-taniguchi** [wasidennis/AdaptSegNet#14]
I tried to learn with my own data set and tried to change the number of classes, but the following error occurred.
The number of classes of  train_gta2cityscapes_multi.py and deeplab_multi.py has already been changed.
class number : From 19 to 1

RuntimeError: Error(s) in loading state_dict for ResNetMulti:
	While copying the parameter named "layer5.conv2d_list.0.weight", whose dimensions in the model are torch.Size([1, 1024, 3, 3]) and whose dimensions in the checkpoint are torch.Size([21, 2048, 3, 3]).
	While copying the parameter named "layer5.conv2d_list.0.bias", whose dimensions in the model are torch.Size([1]) and whose dimensions in the checkpoint are torch.Size([21]).
	While copying the parameter named "layer5.conv2d_list.1.weight", whose dimensions in the model are torch.Size([1, 1024, 3, 3]) and whose dimensions in the checkpoint are torch.Size([21, 2048, 3, 3]).
	While copying the parameter named "layer5.conv2d_list.1.bias", whose dimensions in the model are torch.Size([1]) and whose dimensions in the checkpoint are torch.Size([21]).
	While copying the parameter named "layer5.conv2d_list.2.weight", whose dimensions in the model are torch.Size([1, 1024, 3, 3]) and whose dimensions in the checkpoint are torch.Size([21, 2048, 3, 3]).
	While copying the parameter named "layer5.conv2d_list.2.bias", whose dimensions in the model are torch.Size([1]) and whose dimensions in the checkpoint are torch.Size([21]).
	While copying the parameter named "layer5.conv2d_list.3.weight", whose dimensions in the model are torch.Size([1, 1024, 3, 3]) and whose dimensions in the checkpoint are torch.Size([21, 2048, 3, 3]).
	While copying the parameter named "layer5.conv2d_list.3.bias", whose dimensions in the model are torch.Size([1]) and whose dimensions in the checkpoint are torch.Size([21]).

**Comment by wasidennis** [comment]
If you want to change the number of classes, you would need to re-initialize the parameters of the classifier, i.e, the last layer (layer5 shown above) in the model, as the channel number would be different. In practice, during copying the weights from our provided pre-trained model, you can ignore layer5.
