### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by guyibai** [wasidennis/AdaptSegNet#15]
Hello,Thanks for your shared code.when I train the GTA5-to-Cityscapes model (multi-level) on a GTX 1070 GPU with 8GB memory, there is a problem as follow:

UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train_gta2cityscapes_multi.py", line 413, in <module>
    main()
  File "train_gta2cityscapes_multi.py", line 293, in main
    loss_seg1 = loss_calc(pred1, labels, args.gpu)
  File "train_gta2cityscapes_multi.py", line 145, in loss_calc
    return criterion(pred, label)
  File "/home/student/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/student/AdaptSegNet-master/utils/loss.py", line 34, in forward
    predict = predict[target_mask.view(n, h, w, 1).repeat(1, 1, 1, c)].view(-1, c)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu:58

I tried to use about 2,000 images in total and resized them to 512*216,but the problem still exists.How to solve it?Change the code?
Looking forward to your answer.

**Comment by hfslyc** [comment]
Hi @guyibai,

how do you change the input size to 512*216? if you do it by changing the INPUT_SIZE and INPUT_SIZE_TARGET it should fit in.

**Comment by guyibai** [comment]
Hi @hfslyc ,
I  changed the input size to 640*360 and input_size_target to 512*256.Then I delete every [0] in loss_value,such as loss_D_value1 += loss_D1.data.cpu().numpy()[0].If i dont do this，program would report an error:

  File "train_gta2cityscapes_multi.py", line 304, in main
    loss_seg_value1 += loss_seg1.data.cpu().numpy()[0] / args.iter_size
IndexError: too many indices for array

What will happen to this?

**Comment by hfslyc** [comment]
Hi @guyibai,

This is due to the difference between pytorch 0.2/0.3 and 0.4/up. I think your modification is correct.  But we still recommend you to run this code with pytorch 0.2/0.3.

**Comment by HqWei** [comment]
@guyibai  When you change the image size to 640x320, how is the final MIOU you get ?
