### ISSUE TITLE
About baseline result with res101-deeplabv2

### ISSUE THREAD

**Issue by shanyuhu** [wasidennis/AdaptSegNet#16]
Hi @wasidennis, I use your provided res101 backbone and train deeplab v2 on GTA as your code, Then I evaluate the model on cityscapes, but I only got 31.1 which is far from your baseline result of 36.6. 
Did I miss anything? Looking forward to your reply.

**Comment by shanyuhu** [comment]
@hfslyc

**Comment by shanyuhu** [comment]
Another question is that why the oracle resutls of res101 in Table 2 and Table 5 are  different? 
one is 65.1, and the other is 71.7.

**Comment by tuanhungvu** [comment]
Hi @shanyuhu , I got the same result. I wonder if you solved the problem?

**Comment by shanyuhu** [comment]
@tuanhungvu my final resule is around 34%~35%, still lower than the reported number in the paper

**Comment by tuanhungvu** [comment]
@shanyuhu I see. Did you change anything to get this result (e.g. init LR, params scheduler, optimizer...) ?

**Comment by tarun005** [comment]
@tuanhungvu @shanyuhu I wonder how you solved your problem. I am getting ~29% on baseline ResNet-101.

**Comment by adricarda** [comment]
Did anyone solve the baseline problem? I only get about 29% too.
