### ISSUE TITLE
some questions about the classifier model of deeplab

### ISSUE THREAD

**Issue by zhyx12** [wasidennis/AdaptSegNet#20]
the return statement in forward function of Classifier_Module looks like misaligned. 

https://github.com/wasidennis/AdaptSegNet/blob/e47871be396a08fb10f608889ba85620312d2d24/model/deeplab_multi.py#L114-L118

https://github.com/wasidennis/AdaptSegNet/blob/e47871be396a08fb10f608889ba85620312d2d24/model/deeplab_vgg.py#L17-L21

**Comment by wasidennis** [comment]
Thank you for noticing. This is a bug also later on fixed by the reference repo (link).

The bug is essentially making our model have only 2 effective ASPP layer, and we don't think it will affect the performance much. We will try to re-train the model based on the fixed bug soon.

**Comment by zhyx12** [comment]
Got it. Thanks for your explanation.
