### ISSUE TITLE
Question on model.deeplab_multi.py

### ISSUE THREAD

**Issue by lufi0401** [wasidennis/AdaptSegNet#21]
Hi,

am fascinated by your idea training the segmentation network and trying to reproduce the results. I am studying the deeplab_multi model structure and am a bit confused on the Classifer_Module, specifically on function `Classifier.forward()` on line 114. 

As I understand from the paper that this is the ASPP layer that tries to summarize information at different resolution by convoluting at 4 different rates ([6, 12, 18, 24], 4 feature maps with shape (b, c, w, h)) and then sum the result together (become 1 feature map with shape (b, c, w, h)). In the actual implementation, I notice that `Classifier.forward()` is returned inside the for loop (line 118), which I believe will cause the module to return only the sum of first 2 rates ([6, 12]) instead of 4.

Was that intentional? or did I misunderstand any of the concepts?

Appreciate your answer. Would help me a great deal understanding your work.

Thanks.

**Comment by wasidennis** [comment]
Please check this thread for the issue: https://github.com/wasidennis/AdaptSegNet/issues/20#issuecomment-420142670.
