### ISSUE TITLE
How is the trend of loss changing?

### ISSUE THREAD

**Issue by Sunting78** [wasidennis/AdaptSegNet#22]
I train my data using this method. The loss_adv1 is increased. loss_seg1 and loss_D1 is decreased.  In this situation, should I make LAMBDA_ADV_TARGET1 larger ?

**Comment by wasidennis** [comment]
Looks like the trend of your losses is correct. The adversarial loss will gradually go up, while the discriminator loss will decrease (within a range around 0.2~0.5 is reasonable). However, for obtaining the best performance on your own data, you should still adjust the weights of different losses.

**Comment by Sunting78** [comment]
Thanks for your reply .This is my train log. Please teach me the trend of loss is right? loss_seg1 and loss_D1 is decreased. loss_adv1 is go up.

**Comment by wasidennis** [comment]
@Sunting78 sorry for the late reply and hope you have figured it out! It would be better to train the model much longer for a few thousand iterations and checked the loss trend.
