### ISSUE TITLE
Where is the pretrained model of vgg-16 from?

### ISSUE THREAD

**Issue by mathfinder** [wasidennis/AdaptSegNet#23]
I want to know how to get the pretrained model you use for training. Is it trained on ImageNet by pytorch official? Or is downloaded from here: http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel?

**Comment by wasidennis** [comment]
The pre-trained model in this repo is downloaded from deeplab v2 (ImageNet + COCO ).

**Comment by hfslyc** [comment]
what @wasidennis mentioned is actually for resnet-101. The VGG16 pretrained model is the original imagenet pretrained weight transferred to pytorch format.

you can download it here:
https://github.com/jcjohnson/pytorch-vgg
