### ISSUE TITLE
Any training details for the baseline result?

### ISSUE THREAD

**Issue by ascust** [wasidennis/AdaptSegNet#30]
Hi, I am wondering how you trained the baseline models. Could you provide more details regarding this like the batch-size, lr etc.? Thank you very much.

**Comment by hfslyc** [comment]
Hi,

We use the same hyperparamters for training the baseline and the proposed model.

**Comment by ascust** [comment]
@hfslyc Thanks for the quick reply. So you are saying you used batch-size 1, lr 2.5e-4 num_steps 250k to train the deeplab model with both vgg and resnet101 as the backbone?
Also I am curious that in your code, the dataset class has an argument "scale", which means using random scale, but in the process def __getitem__(self, index), I did not see any random scale steps. Did you actually use random scale or not?

**Comment by wasidennis** [comment]
No, we did not use any random crop or scale, as shown in our code.
