### ISSUE TITLE
Any update info on the migration to pytorch 0.4 version

### ISSUE THREAD

**Issue by amiltonwong** [wasidennis/AdaptSegNet#32]
Hi, @wasidennis ,

Any update info on the migration to pytorch 0.4 version?

**Comment by amiltonwong** [comment]
I see some code [snippet](https://github.com/wasidennis/AdaptSegNet/blob/master/evaluate_cityscapes.py#L110), which mentioned version >=0.4.0.
Is AdaptSegNet ready on pytorch version >=0/4/0?

**Comment by wasidennis** [comment]
We will update the code with pytorch 0.4 soon.
