### ISSUE TITLE
Output size of the discriminator

### ISSUE THREAD

**Issue by cmitash** [wasidennis/AdaptSegNet#37]
Hi Authors,
I was just curious to know what is the size of the output from the discriminator that you used in your experiments. Is it the same as the size of the input (as you mention in the paper). Or is it downsampled? - As the upsampling code was commented out in the file "AdaptSegNet/model/discriminator.py".
In either case, if possible please share some insights into how this could affect the adaptation.

Thanks!

**Comment by wasidennis** [comment]
The output of the discriminator is not upsampled. The upsampled one mentioned in the paper is the output of the segmentation model (generator).

**Comment by CaiziLee** [comment]
@wasidennis But you did mention an upsample layer in discriminator,  right?
![image](https://user-images.githubusercontent.com/6143725/69022968-05ad3c00-09f8-11ea-872a-942862b97958.png)

**Comment by wasidennis** [comment]
@CaiziLee sorry for the misunderstanding. We did try to upsample the final layer, but the results were not affected. In the final implementation as released here, there is no upsampling layer. We will correct it in the paper.
