### ISSUE TITLE
Not enough memory. Buy a new RAM!!!!!

### ISSUE THREAD

**Issue by JIANGbb95** [wasidennis/AdaptSegNet#39]
My RAM is 8G. When I tried to train on my cpu, it says that my computer doesn't have enough memory........
How to solve this problem? Can anyone help me??Thanks!
<img width="943" alt="1111" src="https://user-images.githubusercontent.com/43307030/52528478-9abd2f00-2d1a-11e9-88b3-72cd4871aa97.png">

**Comment by hfslyc** [comment]
Hi,

We suggest to train the model with single GPU with at least 12GB memory, and we do not plan to support CPU training. Thanks
