### ISSUE TITLE
Discriminator of the feature-level adaptation

### ISSUE THREAD

**Issue by LHXXHB** [wasidennis/AdaptSegNet#41]
Hello, thanks for your work! In your paper 'Learning to Adapt Structured Output Space for Semantic Segmentation', you list the comparison between the adaptation in the feature space and output space. But I only found 'discriminator.py' in the directory 'model', which is obviously for the output space adaptation. So, could you please tell me the concrete architecture of discriminator of adaptation in the feature space? Thanks!

**Comment by wasidennis** [comment]
We use the same discriminator for both feature and output space adaptation.

**Comment by LHXXHB** [comment]
Thanks! I also note in another question about the output size, your reply is that the discriminator goes without upsampling layer. So following your setting, if the input feature representation of the discriminator is 1/8 of the original input size, then the discriminator would take 5 downsampling layers with 1/2 each, the final output of the discriminator would be 1/256 ( 1/8 * 1/32) of the original input size. If the target input size is 1024x512 as setted in your experiment, then the discriminator loss would be calculated on the output of 4x2?

**Comment by wasidennis** [comment]
The input to the discriminator is actually upsampled to the size of the original image, so the output of the discriminator is 1/32.

**Comment by LHXXHB** [comment]
Understood and thanks!
