### ISSUE TITLE
License

### ISSUE THREAD

**Issue by allansp84** [wasidennis/AdaptSegNet#44]
Hi Dear,
Could you tell me what is the license of this software, please?
According to _GitHub's Policy_, all repositories without an explicit license are considered Copyrighted materials. Do the authors intend to make this software free?
Thank you!

**Comment by wasidennis** [comment]
@allansp84 the current repo is free only for academic propose.

**Comment by allansp84** [comment]
Thank you, @wasidennis! Could you add a license in your repo that best reflects your desire to make this software free only for academic purpose, please?
Best,
