### ISSUE TITLE
why stopping trainning at num-steps-stop(120000) ?

### ISSUE THREAD

**Issue by idealwei** [wasidennis/AdaptSegNet#48]
I see you set two iteration controller(num-step&num-steps-stop) in your code. Could you explain why you finish trainning at iteration num-steps-stop rather than iteration num-steps.

**Comment by wasidennis** [comment]
It is just for an early stopping strategy to save the resource, as the model is often over-trained (over-fitting to the source data) under the domain adaptation setting. Of course, you can still complete the training, but those models would not be good anyway.
