### ISSUE TITLE
how is this deeplabv2 weight obtained?

### ISSUE THREAD

**Issue by dongzhuoyao** [wasidennis/AdaptSegNet#5]
it seems that you use this weight:

> http://vllab.ucmerced.edu/ytsai/CVPR18/DeepLab_resnet_pretrained_init-f81d91e8.pth

Is this weight the fine-tuned result on PascalVOC Dataset?

**Comment by hfslyc** [comment]
It's the same initial weights used by DeepLabv2 (Imagenet+COCO). It is not PASCAL pretrained.

**Comment by krumo** [comment]
Hi, just for clarification, are the initial weights pretrained on Imagenet or Imagenet+COCO?
