### ISSUE TITLE
Training use batch normalization 

### ISSUE THREAD

**Issue by alphjheon** [wasidennis/AdaptSegNet#52]
Hello, i am trying to train my model after i have enabled batch normalization. Although i have trained my model, when evaluating with cityscapes i got the following error: 

`.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNetMulti:
	Unexpected key(s) in state_dict: "bn1.num_batches_tracked", "layer1.0.bn1.num_batches_tracked", "layer1.0.bn2.num_batches_tracked", "layer1.0.bn3.num_batches_tracked",`

I have also changed the deeplab_multi code in evaluation as in train (for batch normalization)

Is there a special setting i should use?

**Comment by hfslyc** [comment]
Hi,

I think this is an issue related to the pytorch version. maybe you take a look at [this](https://discuss.pytorch.org/t/unexpected-key-in-state-dict-bn1-num-batches-tracked/29454/2) and manually remove the parameters during test time?
