### ISSUE TITLE
Error on when running custom dataset

### ISSUE THREAD

**Issue by anonymous1computervision** [wasidennis/AdaptSegNet#53]
In gta5_dataset.py, 

`        self.id_to_trainid = {7: 0, 8: 1, 11: 2, 12: 3, 13: 4, 17: 5,
                              19: 6, 20: 7, 21: 8, 22: 9, 23: 10, 24: 11, 25: 12,
                              26: 13, 27: 14, 28: 15, 31: 16, 32: 17, 33: 18}`

Can you please explain this?
I am getting the following error.

  D_out2 = model_D2(F.softmax(pred_target2))
exp = ./snapshots/GTA2Cityscapes_single
iter =        0/  250000, loss_seg1 = 1.563 loss_seg2 = 0.762 loss_adv1 = 0.682, loss_adv2 = 0.691 loss_D1 = 0.693 loss_D2 = 0.693
exp = ./snapshots/GTA2Cityscapes_single
iter =        1/  250000, loss_seg1 = 0.786 loss_seg2 = 1.586 loss_adv1 = 0.668, loss_adv2 = 0.659 loss_D1 = 0.693 loss_D2 = 0.693
exp = ./snapshots/GTA2Cityscapes_single
iter =        2/  250000, loss_seg1 = 2.748 loss_seg2 = 0.617 loss_adv1 = 0.690, loss_adv2 = 0.689 loss_D1 = 0.692 loss_D2 = 0.693
exp = ./snapshots/GTA2Cityscapes_single
iter =        3/  250000, loss_seg1 = 0.000 loss_seg2 = 0.000 loss_adv1 = 0.696, loss_adv2 = 0.691 loss_D1 = 0.692 loss_D2 = 0.692
Traceback (most recent call last):
  File "train_ita2stutts_multi.py", line 422, in <module>
    main()
  File "train_ita2stutts_multi.py", line 299, in main
    loss_seg1 = seg_loss(pred1, labels)
  File "/home/red/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/red/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 862, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/red/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1550, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/red/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1409, in nll_loss
    return torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 720, 1280, 3]

**Comment by hfslyc** [comment]
Hi,

the id_to_trainid is used to transform the label indices in the GT to consecutive 0-18 cityscapes training indices.

For you error, the expecting GT shape should look like [1, 720, 1280]. you may want to read your own GT with grayscale?

**Comment by PL-96** [comment]
@anonymous1computervision hi,
I'm a beginner of domain adaptation, could you please tell me how to run custom dataset?
thanks in advance.
