### ISSUE TITLE
Is the initial weights pretrained on Imagenet+COCO?

### ISSUE THREAD

**Issue by krumo** [wasidennis/AdaptSegNet#55]
Hi, thanks for your impressive work! I am trying to reproduce the Baseline(Resnet) on GTA5 to Cityscapes task. I could reproduce the results with the initial weights you provided. However, when I switch to the resnet-101 init weights provided by torchvision, I could only get about 29% meanIOU. 

I tried printing the same layer's batchnorm mean value of these 2 files and found they are not the same. So I want to verify whether you used ImageNet+COCO pretrained weights for all models(baseline+single/multi-level adapted model)? Thanks in advance!

**Comment by wasidennis** [comment]
When using the Imagenet pre-trained model, we used the one converted from Caffe, due to the normalization issue in pytorch provided by torchvision. You can download it from this [link](https://www.dropbox.com/s/87m2lnu3dxfy7o1/resnet101-caffe.pth?dl=0).

**Comment by alphjheon** [comment]
@wasidennis  i downloaded the aforementioned file, but when i try to train the resnet model using it i got error 
"` model.load_state_dict(new_params)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNetMulti:
	Unexpected key(s) in state_dict: "weight", "bias", "running_mean", "running_var", "0.conv1.weight", "0.bn1.weight", "0.bn1.bias", "0.bn1.running_mean", "0.bn1.running_var", "0.conv2.weight", "0.bn2.weight", "0.bn2.bias", "0.bn2.running_mean", "0.bn2.running_var", "0.conv3.weight", "0.bn3.weight", "0.bn3.bias", "0.bn3.running_mean",` " Is any other modification in the code needed in order to start training with ResNet pretrained weight? Thanks in advance
