### ISSUE TITLE
Issue when training discriminator

### ISSUE THREAD

**Issue by YiruS** [wasidennis/AdaptSegNet#59]
Hi there,

Thanks for sharing the code for a better understanding of the paper!

However, I do notice one issue when training discriminator. Specifically, during **single level** mode, if instead I don't do the pred1 from shallow layer, which is opposite to the code's setting that directly put both lambda_adv_target1 and lambda_seg as 0, the loss of discriminator very quickly went to 0. That means the discriminator recognizes the image from source dataset so well, or in other words, does that mean the generator network is weak? Would you have some experience having that issue before?

Thanks and looking forward to your reply!

**Comment by wasidennis** [comment]
In the single-level model, the weight for \lambda_adv_target1 is set to 0, which means that the discriminator1 is not trained (no adversarial loss). In such case, it is fine that the loss of discriminator goes to 0 as we do not need it anymore.

Please let me know whether I answer your question.
