### ISSUE TITLE
Res_Deeplab

### ISSUE THREAD

**Issue by FrancisLeon** [wasidennis/AdaptSegNet#6]
hello,
I wonder in the file train_gta2cityscapes_multi.py line 18: 
```
from model.deeplab_multi import Res_Deeplab 
```
is the same as 
```
from model.deeplab_multi import DeeplabMulti 
```
since I can't find the Res_Deeplab in that file.
Thanks.

**Comment by wasidennis** [comment]
Yes, and it is fixed in train_gta2cityscapes_multi.py. Thanks.
