### ISSUE TITLE
How can I resume from a checkpoint?

### ISSUE THREAD

**Issue by tht106** [wasidennis/AdaptSegNet#61]
Hi,
Thanks for the brilliant work. I am wordering how can I resume from a checkpoint such as "GTA5_25000.pth" after an  interrupt.

**Comment by hfslyc** [comment]
you can resume the training by specify the args `--restore-from your/path/GTA5_25000.pth`.

Note that the learning rate scheduling will be reset. You may need to modify the code if you are trying to recover training after interruption.
