### ISSUE TITLE
Issue about the pixel-wise discriminator

### ISSUE THREAD

**Issue by HanqingXu** [wasidennis/AdaptSegNet#64]
Hi,
  I check the code of the discriminator, and find that the output is not the same size as the input(you comment the upsampling code). So I wonder if the resolution of the output would make a differnence in your practice, and its difference compared with just binary domain classifier (that is , just single-value output). Thanks in advance.

**Comment by hfslyc** [comment]
Hi,

Without the upsampling layer, the output of discriminator is still a 2D map and is not a single value. We found that upsampling the discriminator output does not affect the performance much but introduce slight computation overhead.
