### ISSUE TITLE
Can not reproduce the results on Resnet101-Multi-level

### ISSUE THREAD

**Issue by HanqingXu** [wasidennis/AdaptSegNet#65]
Hello,
    I tried to reproduce the result of resnet101-multi-level, and followed the python3 version. In the end I only got 39.5 mIou on Cityscape compared with 42.4% from the paper (I also trained the baseline with only supervised learning following the exact same hyper-parameter and got 35.95 mIou.). I implemented the whole experiment on 1080Ti , ubuntu 16.04 , torch 0.4.0 and CUDA 8.0. Any advice would be appreciated.

**Comment by wasidennis** [comment]
Hi @HanqingXu, after updating to pytorch > 0.4, we also note that the multi-level model could not be reproduced, and we have not had time to investigate it. At this point, I would suggest using the single-level model and it should give you expected performance.
