### ISSUE TITLE
feature space adaptation

### ISSUE THREAD

**Issue by jianingwangind** [wasidennis/AdaptSegNet#67]
Hi,
thanks for the great work and the codes.
In the original implementation, i only found the output space adaptation, since the both outputs from deeplab_multi are coming from the classifier layers and the upsampled for the later alignment.
So if i want to implement the real feature space adaptation, i should take the feature maps right before the classifier layers, right?
And also a question, the output of from layer5, in my opinion, is not shallow enough,  would aligning the features coming from very shallow layers help the domain adaptation?

looking forward to your reply.

**Comment by wasidennis** [comment]
@jianingwangind yes, if you want to do feature-level adaptation, you should use features before the classifier.

For shallow layers, we have not tried to use them, but in our multi-level model, it also considers a lower-level output and it improves results a bit.

**Comment by jianingwangind** [comment]
@wasidennis thanks a lot for your fast reply:)  May i ask you, in your opinion, how would feature space adaptaion and output space adaptation affect the final performance differently?

**Comment by wasidennis** [comment]
We have shown in the paper that, feature-level adaptation could be less stable during adversarial training. In terms of performance, we also show in the paper that output space adaptation performs better.

**Comment by jianingwangind** [comment]
@wasidennis thanks again for the great reply. Now i get it.
