### ISSUE TITLE
RGB to BGR

### ISSUE THREAD

**Issue by tarun005** [wasidennis/AdaptSegNet#68]
Why is the channel ordering [converted](https://github.com/wasidennis/AdaptSegNet/blob/a31f01ab15942ad6171c6f4ec762d69ddd6a7fb9/dataset/cityscapes_dataset.py#L50) from RGB to BGR? Is there any advantage with this conversion?

**Comment by hfslyc** [comment]
Hi,

We used caffe pretrained weights as network initialization and the original trained model was trained with BGR.
