### ISSUE TITLE
Upscaling discriminator output?

### ISSUE THREAD

**Issue by k4kuz0** [wasidennis/AdaptSegNet#82]
In the paper, under the discriminator section, you write that "An up-sampling layer is added to the last convolution layer for re-scaling the output to the size of the input."

What is the purpose of this upscaling? How would this affect the loss? I can also see that this upscaling is commented out - did you find out that it was unnecessary?

**Comment by wasidennis** [comment]
Sorry for the confusion. We did try to upsample the final layer, but the results were not affected. In the final implementation as released here, there is no upsampling layer.
