### ISSUE TITLE
About Oracle model results

### ISSUE THREAD

**Issue by BinhuiXie** [wasidennis/AdaptSegNet#83]
Why are the oracle resutls of baselines ( based on **VGG-16**) in Table 2 (Table 5) different? In my understanding, all these results are trained on Cityscapes dataset using the same full-supervised model (**VGG-16**), which should be the same. 
Thank you very much!

**Comment by wasidennis** [comment]
There could be still modifications in the architecture, even using the same backbone (e.g., VGG-16). We obtain the oracles as reported or use corresponding architectures in each paper.
