### ISSUE TITLE
Early return issue in model/deeplab*.py

### ISSUE THREAD

**Issue by CharlesJWC** [wasidennis/AdaptSegNet#84]
In the Classifier_Module class, the position of return of forward function is something strange. Is it intended or just the wrong tab?

```
  def forward(self, x):
        out = self.conv2d_list[0](x)
        for i in range(len(self.conv2d_list) - 1):
            out += self.conv2d_list[i + 1](x)
            return out
```

**Comment by wasidennis** [comment]
Please check this [issue](https://github.com/wasidennis/AdaptSegNet/issues/4#issuecomment-391485393).
