### ISSUE TITLE
Question about weight decay 

### ISSUE THREAD

**Issue by trevor-taeyeop** [wasidennis/AdaptSegNet#85]
Thanks for sharing good work. 
I have one simple question about your implementation. 

https://github.com/wasidennis/AdaptSegNet/blob/025a7f54dca681e30fe02327bac46c19dfd8c27c/train_gta2cityscapes_multi.py#L48

Can I asked why you used the 0.0005 instead of 1e-4 which mentioned in the paper section 5.

**Comment by wasidennis** [comment]
Sorry for the confusion. The weight decay we are using should be the one in the implementation. We will fix the typo in the paper.

**Comment by trevor-taeyeop** [comment]
Thanks !!
