### ISSUE TITLE
About the source only model trained on GTA5.

### ISSUE THREAD

**Issue by dlsrbgg33** [wasidennis/AdaptSegNet#87]
Hi,

Thank you for your great contribution to the DA community.

I'd like to ask whether you are able to release the source only pre-trained model (Deeplabv2 / GTA5 / ResNet101).

Thank you very much.

**Comment by wasidennis** [comment]
Please find all the models we have on three benchmark datasets [here](https://www.dropbox.com/s/gpzm15ipyt01mis/DA_Seg_models.zip?dl=0).

The ones with ``*_baseline.pth`` are source-only models.
